### ISSUE TITLE
Some names I am suggesting

### ISSUE THREAD

**Issue by IroncladDev** [Iron-Programming/Graphitron.js#1]
- Micron.js
 - Precision.js
 - Graphitron.js

**Comment by nacochran** [comment]
Thanks! I like Graphitron.js the best. :)

I mostly finished my SVG library as you see, but I plan to make others as
well as time goes on. I am also working on making "tools" to use with those
libraries, such as graphic makers, pixel art engines, etc.

I'm basically going to make a library out of WebGL too... I mean WebGL just
isn't very user friendly so I'm basically going to be making it as friendly
as possible and then just go from there.

**Comment by IroncladDev** [comment]
Okay, great.
